### ISSUE TITLE
不支持鸿蒙吗？

### ISSUE THREAD

**Issue by diwiki2628** [histion/bcgz#8]
![image](https://github.com/histion/bcgz/assets/171202371/dee5b6f3-8a23-41b7-b142-991a2ee0e77b)
二次元小姐姐真好看，边流口水边打飞机了。看看像不像你

**Comment by histion** [comment]
很像你对着你妈鲁冠的样子

**Comment by histion** [comment]
哈哈，好可怜啊，小号被封了总算啃老找到你那东莞的野母讨到了钱注册新号上来找你阔别已久的主子继续尽孝送脸来扇了吗小屌子😋
