### ISSUE TITLE
司马小号小丑一条

### ISSUE THREAD

**Issue by diwiki2628** [histion/bcgz#9]
![image](https://github.com/histion/bcgz/assets/171202371/b7858179-cd4d-4687-b8fb-40ab207cbbc4)
怎么会有人性癖这么奇怪

**Comment by histion** [comment]
哈哈，可怜的小丑，跟条野狗一样认了个爹一直过来叫

**Comment by histion** [comment]
你爹知道你这么卖力在咬人吗，唉，今晚不知道的你能不能骨头哦

**Comment by histion** [comment]
也不知道你给你身首异处的马有没有给你主子这样尽孝🤣
